<<<<<<< HEAD
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
import { Antic_Didone } from 'next/font/google'
import './globals.css'
import Footer from './components/Footer/Footer'



const antic = Antic_Didone({ weight: ['400'],
subsets: ['latin']})


export const metadata = {
  title: 'Sakura Tarot',
  description: 'Juego de Tarot de Sakura Card Carptors',
>>>>>>> feature-footer
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body className={`bg-bg-color bg-bg-Img bg-cover ${antic.className}`}>
        {children}
        <Footer/>
      </body>
>>>>>>> feature-footer
    </html>
  )
}
